version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/eventcatalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6815
      DatabaseServer: mssqlserver
      DatabaseName: CatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "6815:80"
    container_name: eventcatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://catalog
      CartUrl: http://cart
      IdentityUrl: http://192.168.0.23:6700
      CallBackUrl: http://localhost:6811
      OrderUrl: http://order
      StripePublicKey: pk_test_51HEK69FeQjSa1SNf4ZbyJhLyNIUYwApxCfWgdDvPvD6vtKk60h5TnYTnl6M5DBMfkuSNlPLnpUAyxGRC1ubVXl8r00iw2U2h8u
      StripePrivateKey: sk_test_51HEK69FeQjSa1SNf2TqSGtSmen1rCmKpNgRmSuYaS2G3T03tXXFM3rvC4NFwCGzW8R1dRVx7auXXOl20sCN0sDor0041wkldZE
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "6811:80"
    container_name: webeventshop
    networks:
      - frontend
    depends_on:
      - catalog
      - cart
      - tokenserver

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      MvcClient: http://localhost:6811
    ports:
      - "6700:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi
    environment:
      IdentityUrl: http://192.168.0.23:6700
      ConnectionString: basket.data
    ports:
      - "6818:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - tokenserver
      - basket.data

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: events/orderapi
    logging:
      driver: "json-file"
      options: {
        max-size: "200K",
        max-file: "10"
      }
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.0.23:6700
      DatabaseServer: mssqlserver
      DatabaseName: OrdersDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "6813:80"
    container_name: orderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver
      - rabbitmq

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1450:1433"
    container_name: eventsqlserver
    networks:
      - backend

  basket.data:
    image: redis
    container_name: basketdata
    ports:
      - "6081:6379"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: myrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
    networks:
      - backend 